logging:
  level:
    root: INFO
    at.alexwais.cooper: DEBUG
    org.springframework.boot.autoconfigure: ERROR


scenario: ${spring.profiles.active}
loadFixture: ${scenario}.csv

# create a profile configuration ('application-*.yaml') and load fixture csv file (*.csv) for each scenario