dataCenters:
  DC-private:
    onPremise: true
    instanceTypes:
      - label: 4.large
        cpuCores: 4
        memory: 8GB
        count: 2
  DC-1:
    instanceTypes:
      - label: 2.small
        cpuCores: 2
        memory: 2GB
        cost: 0.027
      - label: 2.medium
        cpuCores: 2
        memory: 4GB
        cost: 0.052
      - label: 4.large
        cpuCores: 4
        memory: 8GB
        cost: 0.1
      - label: 4.xlarge
        cpuCores: 4
        memory: 16GB
        cost: 0.19
  DC-2:
    instanceTypes:
      - label: 2.small
        cpuCores: 2
        memory: 2GB
        cost: 0.027
      - label: 2.medium
        cpuCores: 2
        memory: 4GB
        cost: 0.052
      - label: 4.large
        cpuCores: 4
        memory: 8GB
        cost: 0.1
      - label: 4.xlarge
        cpuCores: 4
        memory: 16GB
        cost: 0.19

distance:
  - a: DC-private
    b: DC-private
    latency: 50
  - a: DC-1
    b: DC-1
    latency: 30
  - a: DC-2
    b: DC-2
    latency: 50
  - a: DC-1
    b: DC-2
    latency: 100
  - a: DC-1
    b: DC-private
    latency: 120
  - a: DC-2
    b: DC-private
    latency: 120

services:
  service-gw:
    downstreamServices:
      service-a: 0.5
      service-b: 0.1
    containerConfigurations:
      - label: 1000@512
        rpmCapacity: 1000
        cpuShares: 1024
        memory: 512MB
      - label: 2000@1024
        rpmCapacity: 2000
        cpuShares: 1536
        memory: 1024MB
      - label: 4000@2048
        rpmCapacity: 4000
        cpuShares: 2048
        memory: 2048MB
      - label: 8000@4096
        rpmCapacity: 8000
        cpuShares: 2560
        memory: 4096MB
  service-a:
    downstreamServices:
      service-b: 0.5
    containerConfigurations:
      - label: 600@1024
        rpmCapacity: 600
        cpuShares: 512
        memory: 1024MB
      - label: 900@2048
        rpmCapacity: 900
        cpuShares: 1024
        memory: 2048MB
      - label: 1350@4096
        rpmCapacity: 1350
        cpuShares: 2048
        memory: 4096MB
      - label: 2025@8192
        rpmCapacity: 2025
        cpuShares: 4096
        memory: 8192MB
  service-b:
    containerConfigurations:
      - label: 600@1024
        rpmCapacity: 600
        cpuShares: 512
        memory: 1024MB
      - label: 900@2048
        rpmCapacity: 900
        cpuShares: 1024
        memory: 2048MB
      - label: 1350@4096
        rpmCapacity: 1350
        cpuShares: 2048
        memory: 4096MB
      - label: 2025@8192
        rpmCapacity: 2025
        cpuShares: 4096
        memory: 8192MB