logging:
  level:
    root: INFO
    at.alexwais.cooper: DEBUG
    org.springframework.boot.autoconfigure: ERROR

cooper:
  scenario: ${spring.profiles.active}
  multiplicator: 1
  loadFixture: ${cooper.scenario}@${cooper.multiplicator}x.csv
  optimization:
    algorithm: CPLEX
    enableColocation: true
spring.config.import: ${cooper.scenario}.yml


# For each scenario, a profile configuration ('scenario-*.yaml') and load fixture csv file (scenario-*@*x.csv) is to be created.
# Run Spring Boot using the scenario name as profile to switch between different profiles.