logging:
  level:
    root: INFO
    at.alexwais.cooper: DEBUG
    org.springframework.boot.autoconfigure: ERROR


# For each scenario, a profile configuration ('scenario-*.yaml') and load fixture csv file (scenario-*@*x.csv) is to be created.
# Run the app by setting the following Spring Boot properties at runtime:
scenario: undefined
strategy: GA
multiplicator: 1

cooper:
  scenario: scenario-${scenario}
  scenario-multiplicator: 1
  load-multiplicator: ${multiplicator}
  loadFixture: ${cooper.scenario}@${cooper.load-multiplicator}x.csv
  benchmarkOutput: ${cooper.scenario}@${cooper.load-multiplicator}x_${cooper.optimization.strategy}.csv
  optimization:
    strategy: ${strategy}

spring.config.import: ${cooper.scenario}.yml