logging:
  level:
    root: INFO
    at.alexwais.cooper: DEBUG
    org.springframework.boot.autoconfigure: ERROR


# For each scenario, a profile configuration ('scenario-*.yaml') and load fixture csv file (scenario-*@*x.csv) is to be created.
# Run the app by setting the following Spring Boot properties at runtime:
scenario: undefined
strategy: GA
multiplicator: 1

cooper:
  scenario: scenario-${scenario}
  loadMultiplicator: ${multiplicator}
  scenarioMultiplicator: undefined # defined in scenario Yaml files
  loadFixture: load-fixture/${cooper.scenario}@${cooper.loadMultiplicator}x.csv
  evaluationOutput: evaluation/${cooper.scenario}@${cooper.loadMultiplicator}x_${cooper.optimization.strategy}.csv
  optimization:
    strategy: ${strategy}
    gaLatencyWeight: undefined # defined in scenario Yaml files

spring.config.import: ${cooper.scenario}@${cooper.loadMultiplicator}x.yml