
dataCenters:
  DC-1:
    instanceTypes:
      - label: 1.micro
        cpuCores: 2
        memory: 1024MB
        cost: 0.5
      - label: 2.small
        cpuCores: 2
        memory: 2GB
        cost: 0.5
      - label: 2.medium
        cpuCores: 2
        memory: 2GB
        cost: 0.5
  DC-2:
    instanceTypes:
      - label: 2.medium
        cpuCores: 2
        memory: 1024
        cost: 0.5
      - label: 2.large
        cpuCores: 2
        memory: 1024
        cost: 0.5
      - label: 4.large
        cpuCores: 2
        memory: 1024
        cost: 0.5
services:
  sample-service:
    containerConfigurations:
      - label: 1500@500
        rpmCapacity: 1500
        cpuShares: 1024
        memory: 500MB
      - label: 3000@1500
        rpmCapacity: 3000
        cpuShares: 2048
        memory: 1500MB